name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  deploy:
    runs-on: self-hosted

    steps:
    - name: Run docker compose 
      run: |
        cd /home/ubuntu/martin/cleverspace_test_docker_ec2
        sudo docker compose up -d
    - name: Pull latest Django backend image
      run: |
        cd /home/ubuntu/martin/cleverspace_test_docker_ec2
        sudo docker compose pull backend

    - name: Stop only the Django backend container
      run: |
        cd /home/ubuntu/martin/cleverspace_test_docker_ec2
        sudo docker compose stop backend

    - name: Start backend container with the latest image
      run: |
        cd /home/ubuntu/martin/cleverspace_test_docker_ec2
        sudo docker compose up -d backend

    - name: Remove unused Docker images 
      run: |
        sudo docker image prune -af

    - name: Show active containers
      run: |
        sudo docker container ls
